# Generated by Django 5.1.2 on 2024-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiF1", "0003_alter_team_name_alter_team_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="driverId",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="teamId",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
